# Generated by Django 6.0.6 on 2026-06-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address the reset token was issued for.', max_length=254)),
                ('token', models.CharField(db_index=True, help_text='Cryptographically secure, URL-safe token string.', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False, help_text='Set once the token has been consumed by a confirm request.')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
